import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Box, Drawer, Grid, List, ListItemButton, Typography } from '@mui/material'
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Grid container>
          <Grid item xs={12} md={3} lg={1}>
            <Drawer open anchor="left" variant="permanent">
              <List>
                <ListItemButton>
                  <Link href={"/"}>
                    <Typography variant="body1">Home</Typography>
                  </Link>
                </ListItemButton>
                <ListItemButton>
                  <Link href={"/teams"}>
                    <Typography variant="body1">Teams</Typography>
                  </Link>
                </ListItemButton>
                <ListItemButton>
                  <Link href={"/players"}>
                    <Typography variant="body1">
                      Players</Typography></Link>
                </ListItemButton>
              </List>
            </Drawer>
          </Grid>
          <Grid item xs={12} md={8} lg={10}>
            <Box p={2}>
              {children}
            </Box>
          </Grid>
        </Grid>
      </body>
    </html>
  );
}
